//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class backend {
  public static string GenerateSudoku() {
    string ret = backendPINVOKE.GenerateSudoku();
    return ret;
  }

  public static string GenerateHexSudoku() {
    string ret = backendPINVOKE.GenerateHexSudoku();
    return ret;
  }

  public static void Free(sudokutype type) {
    backendPINVOKE.Free((int)type);
  }

  public static string LoadSudoku() {
    string ret = backendPINVOKE.LoadSudoku();
    return ret;
  }

  public static string LoadHexSudoku() {
    string ret = backendPINVOKE.LoadHexSudoku();
    return ret;
  }

  public static void SaveSudoku() {
    backendPINVOKE.SaveSudoku();
  }

  public static void SaveHexSudoku() {
    backendPINVOKE.SaveHexSudoku();
  }

}
